version: '3'
services:

  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    depends_on:
      - redis

  auth-worker:
    restart: always
    build:
      context: ./auth-worker
      dockerfile: Dockerfile
    environment:
      - C_FORCE_ROOT=true
    environment:
      - TASK_QUEUE=queue1
    depends_on:
      - redis

  redis:
    image: redis
